# Generated by Django 4.1.3 on 2024-09-20 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(default="add a prompt", max_length=10000)),
                (
                    "example_phrases",
                    models.TextField(default="add a phrase", max_length=10000),
                ),
                (
                    "video_url",
                    models.CharField(default="add a video", max_length=10000),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture_url", models.CharField(max_length=10000)),
                (
                    "pronunciation",
                    models.CharField(default="add a sound", max_length=10000),
                ),
                ("is_voiced", models.BooleanField(default=True)),
                ("is_vowel", models.BooleanField(default=True)),
                (
                    "sound_url",
                    models.CharField(default="no sound added yet", max_length=10000),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("photo", models.CharField(max_length=10000)),
                ("about", models.CharField(max_length=50000)),
                ("uid", models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_text", models.CharField(max_length=10000)),
                (
                    "learning_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="latiphonicsapi.learningsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearnItemSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="latiphonicsapi.learningsymbol",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="latiphonicsapi.symbol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="learningsymbol",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="latiphonicsapi.user",
            ),
        ),
    ]
