# Generated by Django 4.2.16 on 2024-11-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latiphonicsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnitemsymbol',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latiphonicsapi.user'),
        ),
    ]
