# Generated by Django 4.1.3 on 2024-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0002_learningsymbol_symbol_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="is_voiced",
            field=models.BooleanField(default=True),
        ),
    ]
