# Generated by Django 4.1.3 on 2024-08-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0002_learningsymbol_symbol_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="is_voiced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="symbol",
            name="pronunciation",
            field=models.CharField(default="add a sound", max_length=100),
        ),
        migrations.CreateModel(
            name="LearnItemSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="latiphonicsapi.learningsymbol",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="latiphonicsapi.symbol",
                    ),
                ),
            ],
        ),
    ]
