# Generated by Django 4.1.3 on 2024-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0003_symbol_is_voiced_symbol_pronunciation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningsymbol",
            name="example_phrases",
            field=models.TextField(default="add a phrase", max_length=200),
        ),
        migrations.AlterField(
            model_name="learningsymbol",
            name="prompt",
            field=models.TextField(default="add a prompt", max_length=200),
        ),
        migrations.AlterField(
            model_name="learningsymbol",
            name="video_url",
            field=models.CharField(default="add a video", max_length=100),
        ),
    ]
