# Generated by Django 4.1.3 on 2024-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0005_remove_user_admin_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="sound_url",
            field=models.CharField(default="no sound added yet", max_length=100),
        ),
    ]
