# Generated by Django 4.1.3 on 2024-09-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0006_symbol_sound_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(max_length=250),
        ),
    ]
