# Generated by Django 4.1.3 on 2024-09-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0007_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(max_length=150),
        ),
    ]
