# Generated by Django 4.1.3 on 2024-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "latiphonicsapi",
            "0009_alter_symbol_picture_url_alter_symbol_pronunciation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="sound_url",
            field=models.CharField(default="no sound added yet", max_length=300),
        ),
    ]
