# Generated by Django 4.1.3 on 2024-09-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0010_alter_symbol_picture_url_alter_symbol_sound_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=3000),
        ),
    ]
