# Generated by Django 4.1.3 on 2024-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0011_alter_symbol_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=13000),
        ),
    ]
