# Generated by Django 4.1.3 on 2024-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0014_alter_learningsymbol_example_phrases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningsymbol",
            name="example_phrases",
            field=models.TextField(default="add a phrase", max_length=400000),
        ),
        migrations.AlterField(
            model_name="learningsymbol",
            name="prompt",
            field=models.TextField(default="add a prompt", max_length=20000000),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_text",
            field=models.CharField(max_length=300000),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=53000),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="pronunciation",
            field=models.CharField(default="add a sound", max_length=8500),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(max_length=80000),
        ),
    ]
