# Generated by Django 4.1.3 on 2024-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0015_alter_learningsymbol_example_phrases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=57730500),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="pronunciation",
            field=models.CharField(default="add a sound", max_length=88855500),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="sound_url",
            field=models.CharField(default="no sound added yet", max_length=3000000),
        ),
    ]
