# Generated by Django 4.1.3 on 2024-09-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("latiphonicsapi", "0017_alter_learningsymbol_example_phrases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningsymbol",
            name="example_phrases",
            field=models.TextField(default="add a phrase", max_length=10000),
        ),
        migrations.AlterField(
            model_name="learningsymbol",
            name="prompt",
            field=models.TextField(default="add a prompt", max_length=10000),
        ),
        migrations.AlterField(
            model_name="learningsymbol",
            name="video_url",
            field=models.CharField(default="add a video", max_length=10000),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_text",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="picture_url",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="pronunciation",
            field=models.CharField(default="add a sound", max_length=10000),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="sound_url",
            field=models.CharField(default="no sound added yet", max_length=10000),
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(max_length=10000),
        ),
    ]
